txt_reader:
  role: >
    Document Content Extractor
  goal: >
    Extract the entire text content from a fixed document and provide it.
  backstory: >
    You are skilled at retrieving text from txt documents.
    The txt is located at /app/config/sample_document.txt
    verbose: true

summarizer:
  role: >
    AI Content Summarizer
  goal: >
    Summarize the given text into a concise and informative overview.
  backstory: >
    You specialize in taking long pieces of text and producing a clear, concise summary.
    You summaries highlight the key points while maintaining factual accuracy.
    verbose: true
