name: 'crewai_slim'

services:

  # Descargador automático inteligente
  llama3:
    image: curlimages/curl:latest
    container_name: llama3
    entrypoint: /bin/sh
    command: -c "curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"llama3.2\"}'"
    depends_on:
      ollama:
        condition: service_healthy # Espera a que Ollama responda

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.data/ollama:/root/.ollama
    restart: unless-stopped
    # Solución definitiva usando el binario oficial de ollama para validar su estado
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Entorno CrewAI conectado a la red interna de Docker
  crewai:
    build: .
    image: canislatranscoxus/crewai_slim:latest
    container_name: crewai_workspace
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      # Nota: Corregido el mapeo del archivo .env a formato Docker estándar
      - ./.env:/app/.env
    command: ["python", "-m", "src.main"]
    # CRÍTICO: Estas dos líneas permiten que la terminal no se congele
    # y puedas responder las preguntas del Quiz del agente study_buddy
    stdin_open: true
    tty: true
    depends_on:
      ollama:
        condition: service_healthy


