name: 'crewai_slim'

services:

    # Descargador automático inteligente (Garantiza que Ollama responda antes de descargar)
  llama3:
    image: curlimages/curl:latest
    container_name: llama3
    entrypoint: /bin/sh
    command: -c "curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"llama3.2\"}'"
    depends_on:
      ollama:
        condition: service_healthy # <--- Espera a que Ollama diga "estoy sano"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.data/ollama:/root/.ollama
    restart: unless-stopped
    # Agrega esto para avisarle a Docker cuándo está lista la API:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 5s
      timeout: 5s
      retries: 5


  # Entorno CrewAI conectado a la red interna de Docker
  crewai:
    build: .
    image: canislatranscoxus/crewai_slim:latest
    container_name: crewai_workspace
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - .env:/app/.env
    command: ["python", "-m", "src.main"]
    depends_on:
      - ollama

